"""initial migration

Revision ID: 0ce227f1d64c
Revises: 
Create Date: 2024-06-02 10:34:08.143884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce227f1d64c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitor_settings', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_monitor_settings_symbol', 'monitoring_types', ['symbol'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'monitor_settings', type_='foreignkey')
    # ### end Alembic commands ###
